### ISSUE TITLE
What about multilanguage?

### ISSUE THREAD

**Issue by parrycima** [liorocks/pingcrm-react#74]
How can we add multi-language support in React.js / Next.js?

**Comment by liorocks** [comment]
@parrycima 

I think this is something that you have to implement on your own at this moment. 

I would suggest to check these repos out: 

https://github.com/codecourse/laravel-inertia-localisation-example
https://github.com/EugeneMeles/laravel-react-i18n
https://github.com/conedevelopment/i18n
https://github.com/laravel/jetstream/issues/232#issuecomment-695145197

Hope it helps!
