### ISSUE TITLE
Support for MySQL

### ISSUE THREAD

**Issue by Harun1302123** [liorocks/pingcrm-react#81]
Please add MySQL support

**Comment by liorocks** [comment]
> You can also use another database (MySQL, Postgres), simply update your configuration accordingly.

See [README.md](https://github.com/liorocks/pingcrm-react)

Just update the environment variables: 

```env
DB_CONNECTION=mysql
DB_HOST=127.0.0.1
DB_PORT=3306
DB_DATABASE=pingcrm
DB_USERNAME=root
DB_PASSWORD=
```
